name: Terraform Apply (main)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: prod    # <-- must match the GitHub Environment you created with required reviewers
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP via OIDC
        id: auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/853065134388/locations/global/workloadIdentityPools/learning-github-actions-pool/providers/learning-github-actions-provider
          service_account: learning-github-actions-sa@rich-torus-428117-m8.iam.gserviceaccount.com
          audience: "https://github.com/lolo-manish-chhetri"
          create_credentials_file: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        working-directory: ./envs/prod
        env:
          TF_S3_BUCKET: ${{ secrets.TF_S3_BUCKET }}
          TF_S3_PREFIX: ${{ secrets.TF_S3_PREFIX }}
        run: |
          cat > backend.hcl <<EOF
          bucket         = "${{ env.TF_S3_BUCKET }}"
          prefix         = "${{ env.TF_S3_PREFIX }}"
          EOF
          terraform init -input=false -backend-config=backend.hcl

      - name: Terraform Apply
        working-directory: ./envs/prod
        run: terraform apply -auto-approve
