name: Terraform PR Plan
on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  id-token: write    # needed for OIDC token (if you plan to auth in PR jobs â€” often not needed for plan)

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/853065134388/locations/global/workloadIdentityPools/learning-github-actions-pool/providers/learning-github-actions-provider"
          service_account: "learning-github-actions-sa@rich-torus-428117-m8.iam.gserviceaccount.com"
          audience: "https://github.com/lolo-manish-chhetri" 

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        working-directory: ./envs/prod
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: ./envs/prod
        env:
          TF_S3_BUCKET: ${{ secrets.TF_S3_BUCKET }}
          TF_S3_PREFIX: ${{ secrets.TF_S3_PREFIX }}
        run: |
          cat > backend.hcl <<EOF
          bucket         = "${{ env.TF_S3_BUCKET }}"
          prefix         = "${{ env.TF_S3_PREFIX }}"
          EOF
          terraform init -input=false -backend-config=backend.hcl


      - name: Terraform Validate
        working-directory: ./envs/prod
        run: terraform validate   

      - name: Terraform Plan
        id: plan
        working-directory: ./envs/prod
        run: terraform plan -no-color -out=tfplan.binary

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./envs/prod/tfplan.binary
